CREATE DATABASE sportcontract;

CREATE TABLE LIGA (
  LigaId int PRIMARY KEY AUTO_INCREMENT,
  Name varchar(255) NOT NULL,
  BucketName varchar(255) NOT NULL,
  FormatNazivFajla varchar(255) NOT NULL,
  SajtId int NOT NULL,
  UrlGuid varchar(255) NOT NULL
);

CREATE TABLE DIVIZIJA (
  DivizijaId int PRIMARY KEY AUTO_INCREMENT,
  LigaId int NOT NULL,
  SajtId int NOT NULL,
  UrlGuid varchar(255) NOT NULL
);

CREATE TABLE TIM (
  TimId int PRIMARY KEY AUTO_INCREMENT,
  SiteName varchar(255),
  SajtId int NOT NULL,
  FileName varchar(255) NOT NULL
);

CREATE TABLE SAJT(
  SajtId int PRIMARY KEY AUTO_INCREMENT,
  Url varchar(255) NOT NULL
);



CREATE TABLE DULTask(
  DULTaskId int PRIMARY KEY AUTO_INCREMENT,
  StatusId int NOT NULL DEFAULT 200,
  ErrorMessage varchar(255),
  TaskStartDateAndTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  TaskEndDateAndTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  LigaId int,
  DivizijaId int,
  HomeTeamId int,
  AwayTeamId int,
  GameDateAndTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

ALTER TABLE LIGA
ADD FOREIGN KEY (SajtId) REFERENCES sajt(SajtId);

ALTER TABLE DIVIZIJA
ADD FOREIGN KEY (LigaId) REFERENCES liga(LigaId),
ADD FOREIGN KEY (SajtId) REFERENCES sajt(SajtId);

ALTER TABLE TIM
ADD FOREIGN KEY (SajtId) REFERENCES sajt(SajtId);

ALTER TABLE DULTASK
ADD FOREIGN KEY (LigaId) REFERENCES LIGA(LigaId);
ALTER TABLE DULTASK
ADD FOREIGN KEY (DivizijaId) REFERENCES DIVIZIJA(DivizijaId);
ALTER TABLE DULTASK
ADD FOREIGN KEY (HomeTeamId) REFERENCES TIM(TimId);
ALTER TABLE DULTASK
ADD FOREIGN KEY (AwayTeamId) REFERENCES TIM(TimId);






